---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kuplyuta/appliances/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH/public
```