---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kuplyuta
    - export PUBLICPATH=/home/kuplyuta/public_html
    # Root folders
    - /bin/cp -R /home/kuplyuta/appliances/config $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp -R /home/kuplyuta/appliances/controllers $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp -R /home/kuplyuta/appliances/core $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp -R /home/kuplyuta/appliances/models $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp -R /home/kuplyuta/appliances/views $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp /home/kuplyuta/appliances/.htaccess $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    - /bin/cp /home/kuplyuta/appliances/parse.py $DEPLOYPATH >> /home/kuplyuta/deploy.log 2>&1
    # Public folder
    - /bin/cp -R /home/kuplyuta/appliances/public/. $PUBLICPATH >> /home/kuplyuta/deploy.log 2>&1
    # Debug task: write success message
    - echo "Deployment finished at $(date)" >> /home/kuplyuta/deploy.log
    