---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kuplyuta
    - /bin/cp -R /home/kuplyuta/appliances/config $DEPLOYPATH
    - /bin/cp -R /home/kuplyuta/appliances/controllers $DEPLOYPATH
    - /bin/cp -R /home/kuplyuta/appliances/core $DEPLOYPATH
    - /bin/cp -R /home/kuplyuta/appliances/models $DEPLOYPATH
    - /bin/cp -R /home/kuplyuta/appliances/views $DEPLOYPATH
    - /bin/cp /home/kuplyuta/appliances/.htaccess $DEPLOYPATH
    - /bin/cp /home/kuplyuta/appliances/parse.py $DEPLOYPATH
    - /bin/cp /home/kuplyuta/appliances/add_seo_fields_migration.sql $DEPLOYPATH
    - export PUBLICPATH=/home/kuplyuta/public_html
    - /bin/cp -R /home/kuplyuta/appliances_/public/. /home/kuplyuta/public_html/

