---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kuplyuta
    - export PUBLICPATH=/home/kuplyuta/public_html
    - /bin/rsync -av --exclude='public' --exclude='.git' --exclude='.cpanel.yml' . $DEPLOYPATH
    - /bin/rsync -av public/ $PUBLICPATH
